'use client';

import { CardContent, CardDescription } from "@/components/ui/card";
import { AccordionItem, Card, CardHeader } from "@nextui-org/react";
import { Accordion, AccordionContent, AccordionTrigger } from "@radix-ui/react-accordion";

export default function HeroSectionFive() {
    return (
        <>
          {/* section 5 - faq */} 
          <section className="flex w-[100vw] gap-3 bg-dprimary px-8 flex flex-col md:flex-row place-items-center sm:place-content-center h-[100vh] py-[10vh] ">

              <div className="h-[100vh] w-[100vw] justify-evenly flex place-items-center place-content-center flex-col text-center gap-2">
                  
                  <div className="flex flex-col w-[70%] place-content-center h-full  gap-7">

                      <h1 className="pt-9 text-main-w sm-pt-0 text-center sm:text-4xl ">
                          Frequently Asked Questions
                        </h1>

                       

                         
                                

                                <Card className="w-[100%] bg-red-300/20 h-[50%] sm:px-3 text-main-w text-left text-[0.5em] sm:text-lg">
                                    Yo!!!
                                    <Accordion type="single" collapsible className="w-[100%] bg-red-300 h-[50%] ">
                                  
                                  <AccordionItem value="item-1">
                                    <AccordionTrigger>What is a JobKompass?</AccordionTrigger>
                                    
                                    <AccordionContent className="text-main-w">
                                    <span className="hover:text-main-w/80">
                                      JobKompass is a software application designed to help
                                      individuals manage and streamline their job search process. I
                                      t includes features such as job listing aggregation,
                                       application tracking, cover letter and introductino generation.
                                    </span>
                                    </AccordionContent>

                                  </AccordionItem>

                                  <AccordionItem value="item-2">
                                    <AccordionTrigger>How can a JobKompass benefit me?</AccordionTrigger>
                                    <AccordionContent className="text-main-w">
                                        <span className="hover:text-main-w/80">It helps you keep track of job applications, deadlines, and application statuses in one centralized location.</span> <br />
                                        {/* <span className="hover:text-main-w/80">It streamlines the job search process by providing easy access to job listings from various sources.</span> <br /> */}
                                        <span className="hover:text-main-w/80">It saves time by automating repetitive tasks, such as finding the right words to say to a recruiter and generating cover letters.</span> <br />
                                        <span className="hover:text-main-w/80">It provides insights and analytics to help you assess your job search progress and optimize your strategy.</span> <br />
                                    </AccordionContent>
                                  </AccordionItem>

                                  <AccordionItem value="item-3">
                                    <AccordionTrigger>How does the AI cover letter generation feature work?</AccordionTrigger>
                                    <AccordionContent className="text-main-w">
                                        <span className="hover:text-main-w/80">
                                        The AI cover letter generation feature utilizes artificial intelligence 
                                        algorithms to analyze job descriptions and user-provided information.
                                        It then generates personalized cover letters tailored to each 
                                        job application, highlighting relevant skills, experiences, 
                                        and achievements.      
                                        </span> <br />
                                    </AccordionContent>
                                  </AccordionItem>

                                  <AccordionItem value="item-4">
                                    <AccordionTrigger>Can I customize the cover letters generated by the AI?</AccordionTrigger>
                                    <AccordionContent className="text-main-w">
                                        <span className="hover:text-main-w/80">
                                        Yes, you have the option to customize the cover letters generated 
                                        by the AI. You can edit the content and  format to better 
                                        reflect your personality and preferences. The AI serves as a starting point, 
                                        providing a foundation that you can modify as needed.
                                        </span> <br />
                                    </AccordionContent>
                                  </AccordionItem>

                                </Accordion>
                                </Card>
                         
                        


                  </div>

              </div>

          </section>
        </>
    )
}